from __future__ import annotations

MAX_ERROR_LOG_KEYS = 512
ERROR_LOG_PRUNE_TARGET = 384
DISABLED_LOOP_WAIT_SECONDS = 1.0
HIDE_REASON_LEGACY = "legacy"
HIDE_REASON_AGGRESSIVE = "aggressive"
DECISION_NONE = "none"
DECISION_WEAK = "weak"
DECISION_STRONG = "strong"
ACTION_NONE = "none"
ACTION_HIDE = "hide"
ACTION_CLOSE = "close"
ACTION_DISMISS_POPUP = "dismiss_popup"
POPUP_GUARD_NA = "n/a"
POPUP_GUARD_ALLOW = "allow"
POPUP_GUARD_BLOCKED = "blocked"
RESTORE_MISS_THRESHOLD = 2
