from __future__ import annotations

from typing import Callable, Protocol

Rect = tuple[int, int, int, int]
WindowIdentity = tuple[int, int, str]


class LayoutApiLike(Protocol):
    def get_window_rect(self, hwnd: int) -> Rect | None: ...

    def update_window(self, hwnd: int) -> bool: ...

    def set_window_pos(
        self,
        hwnd: int,
        x: int,
        y: int,
        width: int,
        height: int,
        flags: int,
    ) -> bool: ...


class Win32ApiLike(LayoutApiLike, Protocol):
    def enum_windows(self, callback: Callable[[int], bool]) -> bool: ...

    def enum_child_windows(self, parent_hwnd: int, callback: Callable[[int], bool]) -> bool: ...

    def get_window_thread_process_id(self, hwnd: int) -> int: ...

    def get_class_name(self, hwnd: int) -> str: ...

    def get_window_text(self, hwnd: int) -> str: ...

    def get_parent(self, hwnd: int) -> int: ...

    def is_window(self, hwnd: int) -> bool: ...

    def is_window_visible(self, hwnd: int) -> bool: ...

    def show_window(self, hwnd: int, cmd: int) -> bool: ...

    def send_message(self, hwnd: int, msg: int, wparam: int = 0, lparam: int = 0) -> int: ...

    def get_last_error(self) -> int: ...


class JoinableThreadLike(Protocol):
    def join(self, timeout: float | None = None) -> object: ...

    def is_alive(self) -> bool: ...


class StatusVarLike(Protocol):
    def set(self, value: str) -> None: ...

    def get(self) -> str: ...


class EngineStateLike(Protocol):
    enabled: bool
    kakao_pid_count: int
    candidate_main_window_count: int
    main_window_count: int
    hidden_windows: int
    closed_windows: int
    resized_windows: int
    last_error: str
    last_tick: float
    restore_failures: int
    last_restore_error: str


class EngineLike(Protocol):
    @property
    def state(self) -> EngineStateLike: ...

    def set_enabled(self, enabled: bool) -> None: ...

    def stop(self) -> None: ...

    def reset_restore_failures(self) -> None: ...

    def set_aggressive_mode(self, enabled: bool) -> None: ...


class RootLike(Protocol):
    def after(self, ms: int, fn: Callable[[], None]) -> object: ...

    def winfo_exists(self) -> bool: ...

    def winfo_viewable(self) -> bool: ...

    def state(self) -> str: ...

    def deiconify(self) -> object: ...

    def lift(self) -> object: ...

    def withdraw(self) -> object: ...

    def quit(self) -> object: ...

    def destroy(self) -> object: ...
